name: Run xcodebuild test

on:
  push:
    branches-ignore:
      - website

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Switch to Xcode 16.2
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Show xcodebuild version
        run: xcodebuild -version

      - name: Show build settings
        run: xcodebuild -showBuildSettings

      - name: Show SDKs
        run: xcodebuild -showsdks

      - name: Show destinations
        run: xcodebuild -scheme ReviewCount -showdestinations

      - name: Install certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Test
        run: xcodebuild -destination platform=macOS -scheme ReviewCount -resultBundlePath test.xcresult test

      - uses: actions/upload-artifact@v4
        with:
          path: test.xcresult
          name: test.xcresult

      - name: Clean up keychain
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
